apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-springboot-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kirankumarhm/test-springboot-argocd.git
    path: k8s/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: testapps
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true